### PR TITLE
Fixes for Linux env

### PR DESCRIPTION
**Pull request by tduccuong**
fix: 
- cannot create an existing folder in linux
- copy copyDirectory do not follow symbolic link

### CODE REVIEW

**Comment by ericroy** [comment]
Aside from the whitespace nightmare, this looks like a legit bug & fix.  👍

**Comment by smelc** [comment]
I was affected by #119 (on Linux) and this commit indeed fixed it, thanks!

**Comment by M-Devloo** [comment]
Pulled in your change, compiled it. Works on Ubuntu 16.04.4 LTS!

**Comment by code-disaster** [comment]
Thank you, but please be careful about auto-reformatting code like that.

Merged in b2601f7.

**Pull request closed without merging**
