### PR TITLE
Changed Java code example to pass correct variable type

### PR DESCRIPTION
**Pull request by stevenmz**
The outDir field in the PackrConfig class is now a File, so the path String must be wrapped in a java.io.File instance.

### CODE REVIEW

**Comment by stevenmz** [comment]
New commit: Added javadoc to the fields in PackrConfig. Used the wording from the README.md file for the most part. This is helpful for people using the API to create the installers.

**Comment by code-disaster** [comment]
I know, this project has no written style guide or contribution guidelines. Nonetheless, I'd like to ask you to avoid commits which contain a lot of format-only changes.

Personally, I wouldn't mind that your plugin/IDE reformats license headers or import statements, but reformatting code causes unnecessary merge conflicts. In this case, for example, I did another fix which now conflicts because your change effectively touched every single line, replacing tabs with spaces.

**Comment by stevenmz** [comment]
Hi Daniel,

I appreciate the feedback as I'm new to contributing to projects on github. You are right, the source formatting is an action I tied to the save action in Netbeans.

I am working on a new component for packr to tie it in better with our automated build system. I hope to send you another commit next week.

Thanks again,
Steven Magana-Zook


_____________________________

**Comment by karlsabo** [comment]
The documentation added by this PR is nice, but considering it's nearly 4 years old, I don't expect a merge and update to happen.

I'm going to close this.

**Pull request closed without merging**
